name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with: { java-version: '17', distribution: 'temurin' }
      - name: Setup Gradle
        run: gradle init --type java-application --dsl gradle
      - name: Build APK
        run: gradle assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v4
        with: { name: HyperOS-Turbo, path: "**/*.apk" }
        
